<template>
  <div class="w3-container" style="background-color: #fdffd6">
    <h3>Italian</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam dignissim, ex vitae commodo faucibus, elit tortor volutpat sem, id pharetra nisl turpis ac purus. Ut aliquet risus rhoncus ullamcorper lobortis. In hac habitasse platea dictumst. Donec nec vehicula augue, ac sodales dolor. Mauris ac feugiat urna, et posuere diam. Praesent porttitor risus hendrerit augue varius iaculis. Vestibulum molestie eget lectus eget tempor. Aliquam sit amet turpis sed dui porttitor ullamcorper eget eu lorem. Quisque tempor dapibus mi, eget facilisis metus venenatis vitae. In sit amet urna aliquet, condimentum urna ac, blandit metus. Morbi vitae odio nisi. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam dui nunc, gravida quis nulla vel, consequat finibus purus. Fusce non tempor ipsum. Vivamus bibendum et enim quis auctor. Ut scelerisque, eros hendrerit porttitor ornare, ex sem molestie massa, ut lobortis erat massa nec elit.</p>

    <p>Fusce placerat ac neque eu pharetra. Morbi mollis arcu sed mi malesuada laoreet. Maecenas maximus blandit eros, vel eleifend lectus imperdiet ut. Donec augue erat, rhoncus vitae gravida et, dignissim at mauris. Curabitur pellentesque fermentum dolor non blandit. Mauris non orci odio. Donec suscipit posuere nisi bibendum viverra.</p>

    <p>Quisque venenatis purus sit amet tempor pretium. Aliquam vulputate a libero eu aliquam. Pellentesque sapien erat, feugiat sit amet bibendum a, ultrices sed nisi. Etiam mollis, odio in commodo pellentesque, mi nulla tristique risus, at aliquet arcu tortor vitae sem. Quisque eget fermentum mi. Maecenas nec ipsum velit. Duis nec ligula augue. Sed nec egestas lorem, vel convallis elit. Vivamus magna est, ultricies vitae venenatis pharetra, viverra vitae nisl. Nunc tristique mattis est, et fermentum felis porta et. Quisque dictum lobortis faucibus. Sed ultrices quis nulla at vestibulum. Sed placerat lorem urna, in venenatis nulla pellentesque sodales. Vestibulum at faucibus neque. Nunc vel purus consectetur, scelerisque urna vitae, vehicula leo. Suspendisse faucibus, purus ac convallis scelerisque, lacus dui finibus elit, non tincidunt magna justo et neque.</p>
  </div>
</template>
